### ISSUE TITLE
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by dai-shi** [hmans/statery#1] opened 2020-12-16 23:30 UTC
Hello! Nice try. Happy to see this lib built for optimizing render with Proxies.
Assuming you would like to get some feedback, here's one case.
I think the api is fine and it's just an implementation matter.

https://codesandbox.io/s/statery-clicker-game-forked-l67qu?file=/src/App.tsx Click "Toggle".

**Comment by hmans** [comment] 2020-12-17 07:17
Yes, this is currently a caveat that I'm not happy about, and as you probably already know, is caused by property accesses to the proxy object invoking React hooks.

The current workaround is to immediately destructure the proxy into the variables you need before using them in expressions (like I'm doing in the example sandbox and the examples in the README), but of course there's an element of surprise to this that I'm not fond of, and do want to fix. I'm just still thinking about how to do it _nicely_.

**Comment by hmans** [comment] 2020-12-17 15:35
Fixed in the upcoming 0.4.0 release.

**Closed as completed by hmans** 2020-12-17 15:35 UTC
Labels: bug

**Comment by dai-shi** [comment] 2020-12-18 07:22
The latest code 05e3452ffda65ae9555655837f9352c22a7d4f14 looks pretty clean.
You might want to use `Set()` as well for listeners which would reduce the bundle size.
